/*
 * Define_LED.h
 *
 *  Created on: 2018. 11. 6.
 *      Author: HJHeo
 *  Revised on: 2018. 11. 19.
 *      Author: Subi
 */

#ifndef DEFINE_LED_H_
#define DEFINE_LED_H_

#ifdef __cplusplus
extern "C" {
#endif

//Parameter Define
#define LEDCOUNT_MAX            5000

#define STATUSLED0_RED_ON       GPIO4Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO0
#define STATUSLED0_RED_OFF      GPIO4Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO0
#define STATUSLED0_YELLOW_ON    GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO12
#define STATUSLED0_YELLOW_OFF   GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO12
#define STATUSLED0_GREEN_ON     GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO11
#define STATUSLED0_GREEN_OFF    GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO11

#define STATUSLED1_RED_ON       GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO10
#define STATUSLED1_RED_OFF      GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO10
#define STATUSLED1_YELLOW_ON    GPIO7Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO22
#define STATUSLED1_YELLOW_OFF   GPIO7Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO22
#define STATUSLED1_GREEN_ON     GPIO7Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO23
#define STATUSLED1_GREEN_OFF    GPIO7Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO23

#define EXPANSION_LED1_ON       GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO13
#define EXPANSION_LED1_OFF      GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO13
#define EXPANSION_LED2_ON       GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO14
#define EXPANSION_LED2_OFF      GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO14
#define EXPANSION_LED3_ON       GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO8
#define EXPANSION_LED3_OFF      GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO8
#define EXPANSION_LED4_ON       GPIO3Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO15
#define EXPANSION_LED4_OFF      GPIO3Regs.GPIO_SETDATAOUT.all   = GPIO_GPIO15

#define SYNC_TEST_GPMC_A0_ON       GPIO7Regs.GPIO_CLEARDATAOUT.all = GPIO_GPIO3;
#define SYNC_TEST_GPMC_A0_OFF      GPIO7Regs.GPIO_SETDATAOUT.all = GPIO_GPIO3;

// Prototype Define.
extern void LED(void);

extern Uint16 LEDCase;

#ifdef __cplusplus
}
#endif

#endif /* DEFINE_LED_H_ */
