/*
 * Mailbox.c
 *
 *  Created on: 2019. 1. 9.
 *      Author: subi
 */


#include "Define_Header.h"

struct HMI_TO_CENTRAL_MASTER HmiCen;

Uint32 MAILBOX_EX_RD[10];
Uint32 MAILBOX_EX_WR[12];
Uint32 MAILBOX_RD_TEST[48];
Uint32 MAILBOX_WR_TEST[30];

Uint16 b = 0, c = 0;

void Mailbox_RD(void)
{
    static int a = 0;

    while(MAILBOX5Regs.MAILBOX_MSGSTATUS_11.bit.NBOFMSGMBM == 0);
    HmiCen.STATUS = MAILBOX2Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM;                    // V_AS
    MAILBOX_RD_TEST[1] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM;                    // V_BS
    MAILBOX_RD_TEST[2] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM;                    // V_CS
    MAILBOX_RD_TEST[3] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[4] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[5] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[6] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[7] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[8] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[9] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[10] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[11] = (float)MAILBOX2Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM;

    MAILBOX_RD_TEST[12] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[13] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[14] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[15] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[16] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[17] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[18] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[19] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[20] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[21] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[22] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[23] = (float)MAILBOX3Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM;

    MAILBOX_RD_TEST[24] = (float)MAILBOX4Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[25] = (float)MAILBOX4Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[26] = MAILBOX4Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[27] = MAILBOX4Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[28] = MAILBOX4Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[29] = MAILBOX4Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[30] = MAILBOX4Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[31] = MAILBOX4Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[32] = MAILBOX4Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[33] = MAILBOX4Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[34] = MAILBOX4Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[35] = MAILBOX4Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM;

    MAILBOX_RD_TEST[36] = MAILBOX5Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[37] = MAILBOX5Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[38] = MAILBOX5Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[39] = MAILBOX5Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[40] = MAILBOX5Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[41] = MAILBOX5Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[42] = MAILBOX5Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[43] = MAILBOX5Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[44] = MAILBOX5Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[45] = MAILBOX5Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[46] = MAILBOX5Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM;
    MAILBOX_RD_TEST[47] = MAILBOX5Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM;

    b= 0;
    for(a = 0; a < 48; a++)
    {
        b += MAILBOX_RD_TEST[a];
    }

//    Mode_Info.all = HmiCen.STATUS;
}

void Mailbox_WR(void)
{

//    theta_t += TIMEBASE1_SAMPLING_TIME * freq_t * PI2;
//    if (theta_t > PI2)         theta_t -= PI2;
//    else if (theta_t < 0)      theta_t += PI2;
//
//    sine_test[1] = (1000*sin(theta_t));
//    sine_test[2] = (-1000*sin(theta_t));
//    sine_test[3] = (900*sin(theta_t));
//    sine_test[4] = (-900*sin(theta_t));
//    sine_test[5] = (800*sin(theta_t));
//    sine_test[6] = (-800*sin(theta_t));
//    sine_test[7] = (700*sin(theta_t));
//    sine_test[8] = (-700*sin(theta_t));
//    sine_test[9] = (600*sin(theta_t));
//    sine_test[10] = (-600*sin(theta_t));
//    sine_test[11] = (500*sin(theta_t));
//    sine_test[12] = (-500*sin(theta_t));
//    sine_test[13] = (400*sin(theta_t));
//    sine_test[14] = (-400*sin(theta_t));
//    sine_test[15] = (300*sin(theta_t));
//    sine_test[16] = (-300*sin(theta_t));
//    sine_test[17] = (200*sin(theta_t));
//    sine_test[18] = (-200*sin(theta_t));


//    MAILBOX_WR_TEST[0] = (Uint32)LEDCase;
//    MAILBOX_WR_TEST[1] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[2] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[3] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[4] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[5] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[6] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[7] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[8] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[9] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[10] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[11] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[12] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[13] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[14] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[15] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[16] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[17] = *(Uint32 *)(&sine_test[1]);
//    MAILBOX_WR_TEST[18] = *(Uint32 *)(&sine_test[1]);

    while(MAILBOX6Regs.MAILBOX_FIFOSTATUS_0.bit.FIFOFULLMBM == 1);
//    MAILBOX6Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM = *(Uint32 *)(&V_AS_sec);
//    MAILBOX6Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM = *(Uint32 *)(&V_BS_sec);
//    MAILBOX6Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM = *(Uint32 *)(&V_CS_sec);
//    MAILBOX6Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM = *(Uint32 *)(&I_AS);
//    MAILBOX6Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM = *(Uint32 *)(&I_BS);
//    MAILBOX6Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM = *(Uint32 *)(&I_CS);
//    MAILBOX6Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM = *(Uint32 *)(&I_AU);
//    MAILBOX6Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM = *(Uint32 *)(&I_AL);
//    MAILBOX6Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM = *(Uint32 *)(&I_BU);
//    MAILBOX6Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM = *(Uint32 *)(&I_BL);
//    MAILBOX6Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM = *(Uint32 *)(&I_CU);
//    MAILBOX6Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM = *(Uint32 *)(&I_CL);
//
//    MAILBOX7Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM = 0;
//    MAILBOX7Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM = 0;
//    MAILBOX7Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM = *(Uint32 *)(&V_DC);
//    MAILBOX7Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM = *(Uint32 *)(&I_DC);
//    MAILBOX7Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM = 0;
//    MAILBOX7Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM = 0;
//    MAILBOX7Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM = 0;

    MAILBOX6Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM = V_AS_sec_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM = V_BS_sec_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM = V_CS_sec_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM = I_AS_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM = I_BS_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM = I_CS_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM = I_AU_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM = I_AL_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM = I_BU_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM = I_BL_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM = I_CU_T.all_U;
    MAILBOX6Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM = I_CL_T.all_U;

    MAILBOX7Regs.MAILBOX_MESSAGE_0.MESSAGEVALUEMBM = 0;
    MAILBOX7Regs.MAILBOX_MESSAGE_1.MESSAGEVALUEMBM = 0;
    MAILBOX7Regs.MAILBOX_MESSAGE_2.MESSAGEVALUEMBM = V_DC_T.all_U;
    MAILBOX7Regs.MAILBOX_MESSAGE_3.MESSAGEVALUEMBM = I_DC_T.all_U;
    MAILBOX7Regs.MAILBOX_MESSAGE_4.MESSAGEVALUEMBM = 0;
    MAILBOX7Regs.MAILBOX_MESSAGE_5.MESSAGEVALUEMBM = 0;
    MAILBOX7Regs.MAILBOX_MESSAGE_6.MESSAGEVALUEMBM = 0;

    MAILBOX7Regs.MAILBOX_MESSAGE_7.MESSAGEVALUEMBM = MAILBOX_EX_WR[0];
    MAILBOX7Regs.MAILBOX_MESSAGE_8.MESSAGEVALUEMBM = MAILBOX_EX_WR[1];
    MAILBOX7Regs.MAILBOX_MESSAGE_9.MESSAGEVALUEMBM = MAILBOX_EX_WR[2];
    MAILBOX7Regs.MAILBOX_MESSAGE_10.MESSAGEVALUEMBM = MAILBOX_EX_WR[3];
    MAILBOX7Regs.MAILBOX_MESSAGE_11.MESSAGEVALUEMBM = MAILBOX_EX_WR[4];
}
